# Generated by Django 5.2.4 on 2025-07-17 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_whatsapp', models.CharField(max_length=20, unique=True)),
                ('estado_conversacion', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialEstadoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_cita', models.CharField(choices=[('Agendado', 'Agendado'), ('Notificado Profesional', 'Notificado Profesional'), ('Pendiente Primer Confirmación 24 Horas', 'Pendiente Primer Confirmación 24 Horas'), ('Primer Confirmado', 'Primer Confirmado'), ('Pendiente Segunda Confirmación 2 Horas', 'Pendiente Segunda Confirmación 2 Horas'), ('Segundo Confirmado', 'Segundo Confirmado'), ('Finalizado', 'Finalizado')], max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_agendable_por_bot', models.BooleanField(default=True)),
                ('duracion_minutos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('tipo_documento', models.CharField(choices=[('Cédula de Ciudadanía', 'Cédula de Ciudadanía'), ('Tarjeta de Identidad', 'Tarjeta de Identidad'), ('NIT', 'NIT')], max_length=30)),
                ('numero_documento', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('celular', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('Cliente', 'Cliente'), ('Profesional', 'Profesional')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_whatsapp', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_acudiente', models.CharField(blank=True, max_length=255, null=True)),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('barrio', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('remitido_colegio', models.BooleanField(default=False)),
                ('colegio', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.estadochat')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_calendar_url_event', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.historialestadocita')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.producto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='citas.usuario')),
                ('profesional_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to='citas.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.producto')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.profesional')),
            ],
            options={
                'unique_together': {('producto', 'profesional')},
            },
        ),
    ]
