# Generated by Django 5.2.4 on 2025-07-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_usuario_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='remitido_colegio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
