# Generated by Django 5.2.4 on 2025-07-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_cliente_remitido_colegio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadochat',
            name='numero_whatsapp',
            field=models.CharField(max_length=20),
        ),
    ]
