# Generated by Django 5.2.4 on 2025-07-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_alter_estadochat_numero_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(max_length=20),
        ),
    ]
