# Generated by Django 5.2.4 on 2025-07-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_alter_usuario_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='last_used',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(db_index=True, help_text='Nombre descriptivo para la API Key', max_length=100),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='usage_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora_fin',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora_inicio',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='barrio',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='colegio',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='edad',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_acudiente',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='remitido_colegio',
            field=models.BooleanField(blank=True, db_index=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='estadochat',
            name='numero_whatsapp',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='historialestadocita',
            name='estado_cita',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Notificado Profesional', 'Notificado Profesional'), ('Pendiente Primer Confirmación 24 Horas', 'Pendiente Primer Confirmación 24 Horas'), ('Primer Confirmado', 'Primer Confirmado'), ('Pendiente Segunda Confirmación 2 Horas', 'Pendiente Segunda Confirmación 2 Horas'), ('Segundo Confirmado', 'Segundo Confirmado'), ('Finalizado', 'Finalizado')], db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='historialestadocita',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='duracion_minutos',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='es_agendable_por_bot',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='cargo',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Profesional', 'Profesional')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('NIT', 'NIT')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['is_active', 'name'], name='apikey_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['-created_at'], name='apikey_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['-last_used'], name='apikey_last_used_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['-usage_count'], name='apikey_usage_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_hora_inicio', 'fecha_hora_fin'], name='cita_horario_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['cliente', 'fecha_hora_inicio'], name='cita_cliente_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['profesional_asignado', 'fecha_hora_inicio'], name='cita_profesional_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['producto', 'fecha_hora_inicio'], name='cita_producto_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado_actual', 'fecha_hora_inicio'], name='cita_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['-fecha_hora_inicio'], name='cita_fecha_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['google_calendar_event_id'], name='cita_calendar_event_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['remitido_colegio', 'colegio'], name='cliente_colegio_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['barrio'], name='cliente_barrio_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['edad'], name='cliente_edad_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['estado_chat'], name='cliente_estado_chat_idx'),
        ),
        migrations.AddIndex(
            model_name='estadochat',
            index=models.Index(fields=['numero_whatsapp'], name='estadochat_whatsapp_idx'),
        ),
        migrations.AddIndex(
            model_name='historialestadocita',
            index=models.Index(fields=['estado_cita', 'fecha_registro'], name='historial_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='historialestadocita',
            index=models.Index(fields=['-fecha_registro'], name='historial_fecha_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['es_agendable_por_bot', 'nombre'], name='producto_agendable_nombre_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['duracion_minutos'], name='producto_duracion_idx'),
        ),
        migrations.AddIndex(
            model_name='productoprofesional',
            index=models.Index(fields=['producto', 'profesional'], name='producto_profesional_idx'),
        ),
        migrations.AddIndex(
            model_name='profesional',
            index=models.Index(fields=['cargo'], name='profesional_cargo_idx'),
        ),
        migrations.AddIndex(
            model_name='profesional',
            index=models.Index(fields=['numero_whatsapp'], name='profesional_whatsapp_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['nombres', 'apellidos'], name='usuario_nombre_completo_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['tipo', 'nombres'], name='usuario_tipo_nombre_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['tipo_documento', 'numero_documento'], name='usuario_documento_idx'),
        ),
    ]
