# Docker Compose para Dokploy - Versión optimizada
# Este archivo está configurado para usar PostgreSQL externo gestionado por Dokploy

services:
  # Aplicación Django
  web:
    build: .
    container_name: orientando_web
    # ports:
      # - "8000:8000"  # Exponer puerto para Dokploy
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      DEBUG: ${DEBUG:-False}
      DJANGO_SETTINGS_MODULE: config.settings
      SECRET_KEY: ${DJANGO_SECRET_KEY:-django-insecure-6*+xxjrz7@1wn1^vz5=!rb=w5m2$e*sc4i52x3_sbb=_@-_x*4}
      ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,orien-prueba.yoyodr.dev}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-https://orien-prueba.yoyodr.dev,http://localhost:8000,http://127.0.0.1:8000}
      # Variables de BD externa (configuradas en Dokploy)
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
    command: >
      sh -c "mkdir -p /app/staticfiles /app/media &&
             echo 'Esperando PostgreSQL externo...' &&
             ./wait-for-postgres.sh $DB_HOST $DB_PORT &&
             echo 'Ejecutando migraciones...' &&
             python manage.py migrate --noinput &&
             echo 'Recolectando archivos estáticos...' &&
             python manage.py collectstatic --noinput --clear --verbosity=2 &&
             echo 'Verificando archivos estáticos...' &&
             ls -la /app/staticfiles/ &&
             test -f /app/staticfiles/admin/css/base.css && echo 'Admin CSS encontrado' || echo 'ERROR: Admin CSS no encontrado' &&
             echo 'Iniciando Gunicorn...' &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 60s
      timeout: 30s
      retries: 3

volumes:
  static_volume:
    driver: local
  media_volume:
    driver: local
